@baseUrl = http://localhost:8080/api/v1

# @name ping
GET {{baseUrl}}/welcome
Content-Type: application/json

###

# @name create_sensors
POST {{baseUrl}}/sensors
Content-Type: application/json

{
    "name": "dummy example"
}

###

# @name fetch_sensors
GET {{baseUrl}}/examples/0767cc1d-c723-4963-8c66-8937721cd514
Content-Type: application/json