@baseUrl = http://localhost:8080/api/v1

# @name ping
GET {{baseUrl}}/welcome
Content-Type: application/json

###

# @name create_sensors
POST {{baseUrl}}/sensors
Content-Type: application/json

{
	"name": "Test Name",
	"description":  "bla bla",
	"sensor_category_name":  "Pressure",
	"equipment_name":  "HVAC",
	"sector_name": "Electrical",
	"observation":"bla bla"
}

###

# @name fetch_sensors
GET {{baseUrl}}/sensors
Content-Type: application/json